[config]
default_to_workspace = false


[tasks.typeshare]
command = "typeshare"
args = [
    "./share",
    "--lang=typescript",
    "--output-file=./share/assemble_type.ts"
]

[tasks.sqlx-prepare]
command = "sqlx"
args = ["prepare", "--workspace"]