/*
 Generated by typeshare 1.9.2
*/

export interface Weapons {
	r_arm: string;
	l_arm: string;
	r_back: string;
	l_back: string;
}

export enum TestEnum {
	HandGan = "HandGan",
	ShotGan = "ShotGan",
}

