/*
 Generated by typeshare 1.9.2
*/

export interface Weapons {
	rArm: string;
	lArm: string;
	rBack: string;
	lBack: string;
}

export interface Frame {
	head: string;
	core: string;
	legs: string;
}

export interface Parts {
	wepons: Weapons;
	frame: Frame;
}

export interface AcAssemble {
	ulid: string;
	pilotName: string;
	acName: string;
	acCardImageUrl: string;
	emblemImageUrl: string;
	acImageUrls: string[];
	paarts: Parts;
	description: string;
	remarks: string;
}

