[package]
name = "share"
version = "0.1.0"
edition = "2021"

[dependencies]
ulid = { workspace=true , features = ["serde"]}
serde.workspace = true
# serde_json.workspace = true
utoipa.workspace = true

typeshare = "1.0"